import { afterEach,describe,expect,it } from "vitest";
import type { PronunciationService } from "../src/core/providers.js";
import { testContext } from "./helpers.js";
const contexts:Array<Awaited<ReturnType<typeof testContext>>>=[];afterEach(async()=>{while(contexts.length)await contexts.pop()!.close();});
const provider:PronunciationService={configured:true,provider:"test-pronunciation",async assess(){return{status:"READY",overallScore:83,pronunciationScore:86,fluencyScore:79,rhythmScore:83,words:[{word:"Learning",score:92,status:"good"},{word:"language",score:61,status:"poor"}]};}};
describe("pronunciation and auth",()=>{
  it("maps and persists a configured provider response",async()=>{const c=await testContext({pronunciation:provider});contexts.push(c);const response=await c.app.inject({method:"POST",url:"/api/pronunciation/assess",headers:c.headers,payload:{expectedText:"Learning language",language:"en",audioBase64:"ZmFrZQ=="}});expect(response.statusCode).toBe(200);expect(response.json().data).toMatchObject({overallScore:83,words:[{status:"good"},{status:"poor"}]});const weakest=await c.app.inject({method:"GET",url:"/api/pronunciation/weakest",headers:c.headers});expect(weakest.json().data[0].word).toBe("language");});
  it("reports NOT_CONFIGURED instead of fake scores",async()=>{const c=await testContext();contexts.push(c);const availability=await c.app.inject({method:"GET",url:"/api/pronunciation/availability",headers:c.headers});expect(availability.json().data.status).toBe("NOT_CONFIGURED");const response=await c.app.inject({method:"POST",url:"/api/pronunciation/assess",headers:c.headers,payload:{expectedText:"hello",language:"en",audioBase64:"ZmFrZQ=="}});expect(response.statusCode).toBe(503);expect(response.json().error.code).toBe("SERVICE_NOT_CONFIGURED");});
  it("isolates protected resources by authenticated user",async()=>{const c=await testContext();contexts.push(c);const unauth=await c.app.inject({method:"GET",url:"/api/vocabulary"});expect(unauth.statusCode).toBe(401);const other=await c.app.inject({method:"POST",url:"/api/auth/register",payload:{name:"Other",email:"other@example.com",password:"password123"}});const token=other.json().data.token;const created=await c.app.inject({method:"POST",url:"/api/vocabulary",headers:c.headers,payload:{language:"en",term:"secret",meaningVi:"bí mật"}});const itemId=created.json().data.item.id;const forbidden=await c.app.inject({method:"GET",url:`/api/vocabulary/${itemId}`,headers:{authorization:`Bearer ${token}`}});expect(forbidden.statusCode).toBe(404);});
});
