import type { Database } from "../db/database.js";
import type { Language } from "../shared/schemas.js";

interface StatusCount { status:string; count:number }
const today=()=>new Date().toISOString().slice(0,10);
export const isActiveDay=(activity:{vocabularyReviews:number;quizzes:number;readingMinutes:number;shadowingMinutes:number;pronunciationAttempts:number})=>activity.vocabularyReviews>=1||activity.quizzes>=1||activity.readingMinutes>=5||activity.shadowingMinutes>=3||activity.pronunciationAttempts>=1;

export class ProgressService {
  constructor(private readonly db:Database){}
  dashboard(userId:string){return{languages:{en:this.language(userId,"en"),zh:this.language(userId,"zh")},global:this.global(userId)};}
  language(userId:string,language:Language){
    const total=this.db.get<{count:number}>("SELECT COUNT(*) count FROM vocabulary_items WHERE user_id=? AND language=?",userId,language)?.count??0;
    const counts=Object.fromEntries(this.db.all<StatusCount>("SELECT p.status,COUNT(*) count FROM vocabulary_progress p JOIN vocabulary_items v ON v.id=p.vocabulary_id WHERE v.user_id=? AND v.language=? GROUP BY p.status",userId,language).map(r=>[r.status,r.count]));
    const due=this.db.get<{count:number}>("SELECT COUNT(*) count FROM vocabulary_progress p JOIN vocabulary_items v ON v.id=p.vocabulary_id WHERE v.user_id=? AND v.language=? AND p.next_review_at<=? AND p.status!='MASTERED'",userId,language,new Date().toISOString())?.count??0;
    const quiz=this.db.get<{accuracy:number|null}>("SELECT AVG(score) accuracy FROM quiz_sessions WHERE user_id=? AND language=? AND status='COMPLETED'",userId,language)?.accuracy??0;
    const pronunciation=this.db.get<{average:number|null;tone:number|null}>("SELECT AVG(score) average,AVG(tone_accuracy) tone FROM pronunciation_attempts WHERE user_id=? AND language=?",userId,language);
    const readings=this.db.get<{count:number}>("SELECT COUNT(*) count FROM readings WHERE user_id=? AND language=?",userId,language)?.count??0;
    const shadowing=this.db.get<{minutes:number|null}>("SELECT SUM(shadowing_minutes) minutes FROM study_activities WHERE user_id=?",userId)?.minutes??0;
    return{totalWords:total,mastered:counts.MASTERED??0,learning:(counts.LEARNING??0)+(counts.REVIEW??0),new:counts.NEW??0,dueToday:due,quizAccuracy:Number(Number(quiz).toFixed(1)),pronunciationAverage:Number(Number(pronunciation?.average??0).toFixed(1)),shadowingMinutes:shadowing,readingCompleted:readings,...(language==="zh"?{toneAccuracy:Number(Number(pronunciation?.tone??0).toFixed(1))}:{})};
  }
  global(userId:string){const activity=this.db.get<{vocabulary_reviews:number;quizzes:number;reading_minutes:number;shadowing_minutes:number;pronunciation_attempts:number;study_seconds:number}>("SELECT * FROM study_activities WHERE user_id=? AND activity_date=?",userId,today());const settings=this.db.get<{daily_goal:number}>("SELECT daily_goal FROM user_settings WHERE user_id=?",userId);const completed=(activity?.vocabulary_reviews??0)+(activity?.quizzes??0)+(activity?.pronunciation_attempts??0)+(activity?.reading_minutes??0)+(activity?.shadowing_minutes??0);const totalSeconds=this.db.get<{total:number|null}>("SELECT SUM(study_seconds) total FROM study_activities WHERE user_id=?",userId)?.total??0;return{streak:this.streak(userId),todayGoal:settings?.daily_goal??20,todayCompleted:completed,totalStudyTimeSeconds:totalSeconds};}
  streak(userId:string,reference=new Date()){const rows=this.db.all<{activity_date:string;vocabulary_reviews:number;quizzes:number;reading_minutes:number;shadowing_minutes:number;pronunciation_attempts:number}>("SELECT * FROM study_activities WHERE user_id=? ORDER BY activity_date DESC",userId);const active=new Set(rows.filter(r=>isActiveDay({vocabularyReviews:r.vocabulary_reviews,quizzes:r.quizzes,readingMinutes:r.reading_minutes,shadowingMinutes:r.shadowing_minutes,pronunciationAttempts:r.pronunciation_attempts})).map(r=>r.activity_date));let cursor=new Date(Date.UTC(reference.getUTCFullYear(),reference.getUTCMonth(),reference.getUTCDate()));if(!active.has(cursor.toISOString().slice(0,10)))cursor.setUTCDate(cursor.getUTCDate()-1);let count=0;while(active.has(cursor.toISOString().slice(0,10))){count++;cursor.setUTCDate(cursor.getUTCDate()-1);}return count;}
  todayPlan(userId:string){const s=this.db.get<{english_new_words_target:number;chinese_new_words_target:number;review_target:number;quiz_target:number;shadowing_target:number}>("SELECT * FROM user_settings WHERE user_id=?",userId)!;const planFor=(language:Language,newTarget:number)=>{const available=this.db.get<{count:number}>("SELECT COUNT(*) count FROM vocabulary_items v JOIN vocabulary_progress p ON p.vocabulary_id=v.id WHERE v.user_id=? AND v.language=? AND p.status='NEW'",userId,language)?.count??0;const due=this.db.get<{count:number}>("SELECT COUNT(*) count FROM vocabulary_items v JOIN vocabulary_progress p ON p.vocabulary_id=v.id WHERE v.user_id=? AND v.language=? AND p.next_review_at<=?",userId,language,new Date().toISOString())?.count??0;return{newWords:{target:newTarget,available},dueReviews:{target:s.review_target,available:due},quiz:{target:s.quiz_target},shadowing:{targetMinutes:s.shadowing_target}};};return{date:today(),english:planFor("en",s.english_new_words_target),chinese:{...planFor("zh",s.chinese_new_words_target),pinyin:{target:s.quiz_target}}};}
}
