import { randomUUID } from "node:crypto";
import type { Database } from "../db/database.js";
import { errors } from "../shared/errors.js";
import { buildGameItems, isGameType, publicGameItem, scoreGameAnswer, type GeneratedGameItem } from "../shared/gameModes.js";
import type { Language } from "../shared/schemas.js";

export interface QuizQuestion { id:string;prompt:string;audioText?:string;options?:string[];answer:string;type:string;vocabularyId?:string }
const normalizeAnswer=(value:string)=>value.normalize("NFKC").trim().toLocaleLowerCase();
export function scoreAnswer(expected:string,actual:string):boolean{return normalizeAnswer(expected)===normalizeAnswer(actual);}

export class QuizService {
  constructor(private readonly db:Database){}
  start(userId:string,input:{language:Language;type:string;count:number}){
    const allowed=input.language==="en"?["TERM_TO_MEANING","MEANING_TO_TERM","FILL_BLANK","LISTENING","CONTEXT","READING_COMPREHENSION"]:["HANZI_TO_MEANING","MEANING_TO_HANZI","HANZI_TO_PINYIN","PINYIN_TO_HANZI","TONE_SELECTION","LISTENING","CONTEXT"];
    if(!allowed.includes(input.type))throw errors.validation(`Quiz type ${input.type} is not valid for ${input.language}`);
    const rows=this.db.all<{id:string;term:string;meaning_vi:string;pronunciation:string|null;metadata_json:string}>("SELECT id,term,meaning_vi,pronunciation,metadata_json FROM vocabulary_items WHERE user_id=? AND language=? ORDER BY RANDOM() LIMIT ?",userId,input.language,input.count);
    if(!rows.length)throw errors.validation("No vocabulary is available for this quiz");
    const questions:QuizQuestion[]=rows.flatMap(row=>{const metadata=JSON.parse(row.metadata_json) as Record<string,unknown>;let prompt=row.term,answer=row.meaning_vi,audioText:string|undefined;if(["MEANING_TO_TERM","MEANING_TO_HANZI"].includes(input.type)){prompt=row.meaning_vi;answer=row.term;}if(input.type==="HANZI_TO_PINYIN"){answer=String(metadata.pinyin??row.pronunciation??"");}if(input.type==="PINYIN_TO_HANZI"){prompt=String(metadata.pinyin??row.pronunciation??"");answer=row.term;}if(input.type==="TONE_SELECTION"){const tones=Array.isArray(metadata.toneData)?metadata.toneData.map(tone=>tone===0?"neutral":String(tone)).join(" "):undefined;answer=String(metadata.tone??tones??"");}if(input.type==="LISTENING"){prompt="Nghe và nhập nghĩa tiếng Việt";audioText=row.term;}if(!answer.trim())return[];return[{id:randomUUID(),prompt,audioText,answer,type:input.type,vocabularyId:row.id}];});
    if(!questions.length)throw errors.validation("No vocabulary has the metadata required for this quiz type");
    const id=randomUUID(),startedAt=new Date().toISOString();this.db.run("INSERT INTO quiz_sessions(id,user_id,language,type,questions_json,total_questions,started_at) VALUES(?,?,?,?,?,?,?)",id,userId,input.language,input.type,JSON.stringify(questions),questions.length,startedAt);return this.publicSession(userId,id);
  }
  answer(userId:string,id:string,answer:string){const row=this.row(userId,id);if(row.status!=="ACTIVE")throw errors.conflict("Quiz session is already completed");const questions=JSON.parse(row.questions_json) as QuizQuestion[];const question=questions[row.current_index];if(!question)throw errors.conflict("Quiz has no current question");const correct=scoreAnswer(question.answer,answer),next=row.current_index+1,done=next>=row.total_questions,newCorrect=row.correct+(correct?1:0),newIncorrect=row.incorrect+(correct?0:1),score=Math.round(newCorrect/row.total_questions*100);this.db.run("UPDATE quiz_sessions SET current_index=?,correct=?,incorrect=?,score=?,status=?,completed_at=? WHERE id=?",next,newCorrect,newIncorrect,score,done?"COMPLETED":"ACTIVE",done?new Date().toISOString():null,id);if(done){const date=new Date().toISOString().slice(0,10);this.db.run("INSERT INTO study_activities(user_id,activity_date,quizzes) VALUES(?,?,1) ON CONFLICT(user_id,activity_date) DO UPDATE SET quizzes=quizzes+1",userId,date);}return{correct,expectedAnswer:question.answer,session:this.publicSession(userId,id)};}
  private row(userId:string,id:string){const row=this.db.get<{id:string;language:string;type:string;questions_json:string;total_questions:number;current_index:number;correct:number;incorrect:number;score:number;status:string;started_at:string;completed_at:string|null}>("SELECT * FROM quiz_sessions WHERE id=? AND user_id=?",id,userId);if(!row)throw errors.notFound("Quiz session");return row;}
  private publicSession(userId:string,id:string){const row=this.row(userId,id),questions=JSON.parse(row.questions_json) as QuizQuestion[],current=questions[row.current_index];if(!current)return{id:row.id,language:row.language,type:row.type,totalQuestions:row.total_questions,currentIndex:row.current_index,correct:row.correct,incorrect:row.incorrect,score:row.score,status:row.status,startedAt:row.started_at,completedAt:row.completed_at,currentQuestion:null};const{answer:_,...publicQuestion}=current;return{id:row.id,language:row.language,type:row.type,totalQuestions:row.total_questions,currentIndex:row.current_index,correct:row.correct,incorrect:row.incorrect,score:row.score,status:row.status,startedAt:row.started_at,completedAt:row.completed_at,currentQuestion:publicQuestion};}
}

export class GameService {
  constructor(private readonly db:Database){}
  start(userId:string,input:{language:Language;type:string;count:number;timerSeconds?:number}){if(!isGameType(input.type))throw errors.validation(`Game type ${input.type} is not valid`);const vocab=this.db.all<{id:string;term:string;meaning_vi:string}>("SELECT id,term,meaning_vi FROM vocabulary_items WHERE user_id=? AND language=? ORDER BY RANDOM() LIMIT ?",userId,input.language,input.count);if(vocab.length<2)throw errors.validation("At least two vocabulary items are required");const items=buildGameItems(input.type,vocab.map(item=>({id:item.id,term:item.term,meaningVi:item.meaning_vi})),randomUUID);const id=randomUUID(),startedAt=new Date().toISOString();this.db.run("INSERT INTO game_sessions(id,user_id,language,type,state_json,timer_seconds,started_at) VALUES(?,?,?,?,?,?,?)",id,userId,input.language,input.type,JSON.stringify({items,currentIndex:0}),input.timerSeconds??(input.type==="SPEED_CHALLENGE"?45:null),startedAt);return this.get(userId,id);}
  get(userId:string,id:string){const row=this.db.get<{id:string;language:string;type:string;state_json:string;score:number;timer_seconds:number|null;status:string;started_at:string;completed_at:string|null}>("SELECT * FROM game_sessions WHERE id=? AND user_id=?",id,userId);if(!row)throw errors.notFound("Game session");const state=JSON.parse(row.state_json) as {items:GeneratedGameItem[];currentIndex:number};const current=state.items[state.currentIndex];return{id:row.id,language:row.language,type:row.type,score:row.score,timerSeconds:row.timer_seconds,status:row.status,startedAt:row.started_at,completedAt:row.completed_at,currentItem:current?publicGameItem(current):null,completedCount:state.currentIndex};}
  answer(userId:string,id:string,itemId:string,answer:string){const row=this.db.get<{state_json:string;score:number;status:string}>("SELECT state_json,score,status FROM game_sessions WHERE id=? AND user_id=?",id,userId);if(!row)throw errors.notFound("Game session");if(row.status!=="ACTIVE")throw errors.conflict("Game session is already completed");const state=JSON.parse(row.state_json) as {items:GeneratedGameItem[];currentIndex:number};const item=state.items[state.currentIndex];if(!item||item.id!==itemId)throw errors.validation("Answer does not match current game item");const correct=scoreGameAnswer(item.answer,answer);item.answered=true;state.currentIndex+=1;const done=state.currentIndex>=state.items.length;this.db.run("UPDATE game_sessions SET state_json=?,score=?,status=?,completed_at=? WHERE id=?",JSON.stringify(state),row.score+(correct?10:0),done?"COMPLETED":"ACTIVE",done?new Date().toISOString():null,id);return{correct,expectedAnswer:item.answer,session:this.get(userId,id)};}
}
